[package]
name = "codec"
version = "0.1.0"
edition = "2021"

[dependencies]


#[dev-dependencies]
#criterion = { version = "0.5", features = ["html_reports"] }
#criterion-cycles-per-byte = "0.6"
#
#[[bench]]
#name = "rizz64"
#harness = false